site_name: Duolingo
repo_name: '2019.2-Duolingo'
repo_url: 'https://github.com/Requisitos2-2019/2019.2-Duolingo'

theme:
  name: 'material'
  language: 'pt'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'green'
    accent: 'green'

nav:
  - Início: index.md
  - Planejamento: 
    - Metodologia: planejamento/Metodologia.md
    - Roadmap: planejamento/Roadmap.md
  - Pré-Rastriabilidade:
    - Rich Picture: prerastriabilidade/RichPicture.md
  - Elicitação:
    - Análise de Protocolo: elicitacao/AnaliseDeProtocolo.md
    - Brainstorming: elicitacao/Brainstorming.md
    - Entrevista: elicitacao/Entrevista.md
    - Instrospecção: elicitacao/Instrospeccao.md
    - Questionário: elicitacao/Questionario.md
    - Storytelling: elicitacao/Storytelling.md
  #   - Prototipação: elicitacao/Prototipacao.md
  #   - Observação: elicitacao/Observacao.md
  #   - Etnografia: elicitacao/Etnografia.md
  #  - Modelagem:
  #  - Análise:
  #  - Pós-Rastreabilidade: 
  
